---------------------------------------
Begin Slurm Prolog: Apr-20-2023 18:11:35
Job ID:    1706623
User ID:   bxia34
Account:   gts-jw254-coda20
Job name:  test_main_py
Partition: gpu-v100
QOS:       inferno
---------------------------------------

CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



The following have been reloaded with a version change:
  1) anaconda3/2022.05.0.1 => anaconda3/2022.05

/storage/home/hcoda1/3/bxia34/.conda/envs/SETI/lib/python3.11/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
/storage/home/hcoda1/3/bxia34/.conda/envs/SETI/lib/python3.11/site-packages/torch/nn/functional.py:1967: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
preparing data
(2784, 1, 819, 256)
Feature size: torch.Size([2784, 1, 819, 256])
Label size: torch.Size([2784])
(556, 1, 819, 256)
Feature size: torch.Size([556, 1, 819, 256])
Label size: torch.Size([556])
Train Epoch: 1 [0/2784 (0%)]	Loss: 0.938476
Traceback (most recent call last):
  File "/storage/coda1/p-jw254/0/bxia34/SETI_CNN/ModelSetup/main.py", line 86, in <module>
    train_seti()
  File "/storage/coda1/p-jw254/0/bxia34/SETI_CNN/ModelSetup/main.py", line 78, in train_seti
    test_accuracy = test(model, test_loader, device)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/coda1/p-jw254/0/bxia34/SETI_CNN/ModelSetup/main.py", line 35, in test
    pred = output.argmax(dim=1, keepdim=True)  # get the index of the max log-probability
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
srun: error: atl1-1-02-009-34-0: task 0: Exited with exit code 1
---------------------------------------
Begin Slurm Epilog: Apr-20-2023 18:27:35
Job ID:        1706623
Array Job ID:  _4294967294
User ID:       bxia34
Account:       gts-jw254-coda20
Job name:      test_main_py
Resources:     cpu=12,gres/gpu:v100=1,mem=128G,node=1
Rsrc Used:     cput=03:12:00,vmem=9252K,walltime=00:16:00,mem=8064K,energy_used=0
Partition:     gpu-v100
QOS:           inferno
Nodes:         atl1-1-02-009-34-0
---------------------------------------
